name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Build site
        run: |
          # Copy frontend files to build directory
          mkdir -p _site
          cp -r frontend/* _site/
          
          # Create a proper index.html at root if needed
          if [ ! -f "_site/index.html" ]; then
            cp frontend/index.html _site/index.html
          fi
          
          # Create a simple landing page that links to all tools
          cat > _site/README.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
              <title>Media Harvest - Content Extraction Tools</title>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <style>
                  body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; line-height: 1.6; }
                  .tool-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; margin: 30px 0; }
                  .tool-card { border: 1px solid #ddd; padding: 20px; border-radius: 8px; text-decoration: none; color: inherit; transition: transform 0.2s; }
                  .tool-card:hover { transform: translateY(-2px); box-shadow: 0 4px 8px rgba(0,0,0,0.1); }
                  .tool-title { font-size: 1.3em; font-weight: bold; margin-bottom: 10px; color: #333; }
                  .tool-desc { color: #666; }
                  h1 { color: #2c3e50; text-align: center; }
                  .subtitle { text-align: center; color: #7f8c8d; margin-bottom: 40px; }
              </style>
          </head>
          <body>
              <h1>🎬 Media Harvest</h1>
              <p class="subtitle">Bulk content extraction and download tools</p>
              
              <div class="tool-grid">
                  <a href="index.html" class="tool-card">
                      <div class="tool-title">📺 YouTube Transcript Extractor</div>
                      <div class="tool-desc">Extract transcripts from YouTube videos in bulk</div>
                  </a>
                  
                  <a href="simple_extractor.html" class="tool-card">
                      <div class="tool-title">🔗 URL to Markdown</div>
                      <div class="tool-desc">Convert URLs to markdown links with metadata</div>
                  </a>
                  
                  <a href="reddit_downloader.html" class="tool-card">
                      <div class="tool-title">📱 Reddit Downloader</div>
                      <div class="tool-desc">Bulk download Reddit content and media</div>
                  </a>
                  
                  <a href="debug_frontend.html" class="tool-card">
                      <div class="tool-title">🔧 Debug Tools</div>
                      <div class="tool-desc">Test backend connectivity and debug issues</div>
                  </a>
              </div>
              
              <p style="text-align: center; margin-top: 40px; color: #888;">
                  <strong>Note:</strong> For full functionality, you'll need to run the backend server locally or deploy it separately.
              </p>
          </body>
          </html>
          EOF
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 